<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Plugin webservice functions.
 *
 * @package    local_wsmanager
 * @copyright  2023 Lilia Smirnova <lilia.pro@protonmail.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_wsmanager_webservice_dashboard_info_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_dashboard_info_output',
        'classpath' => '',
        'description' => 'Summary webservices status',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservices_state_switch' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservices_state_switch',
        'classpath' => '',
        'description' => 'Switching webservices global status: enable/disable',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservices_protocol_switch' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservices_protocol_switch',
        'classpath' => '',
        'description' => 'Switch webservices protocol status: enable/disable',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_protocol_status_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_protocol_status_output',
        'classpath' => '',
        'description' => 'Webservices protocol status output',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_request_info' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'request_info',
        'classpath' => '',
        'description' => 'External function request info',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_dashboard_mobile_info_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_dashboard_mobile_info_output',
        'classpath' => '',
        'description' => 'Mobile webservice status: warning errors if exists',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_mobile_state_switch' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_mobile_state_switch',
        'classpath' => '',
        'description' => 'Switch mobile webservice status: enable/disable',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_documentation_switch' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_documentation_switch',
        'classpath' => '',
        'description' => 'Switch webservices documentation status: enable/disable',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservices_enable_fix' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservices_enable_fix',
        'classpath' => '',
        'description' => 'Fix webservices settings to enable',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_test_create' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_test_create',
        'classpath' => '',
        'description' => 'Test webservice create',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_test_dashboard_table_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_test_dashboard_table_output',
        'classpath' => '',
        'description' => 'Test webservice data table output',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_nav_title' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_nav_title',
        'classpath' => '',
        'description' => 'Webservice navigation title',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_external_function_handle' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'external_function_handle',
        'classpath' => '',
        'description' => 'Handle external function',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_external_function_test_handle' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'external_function_test_handle',
        'classpath' => '',
        'description' => 'Handle external test function',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
    ],
    'local_wsmanager_external_function_handle_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'external_function_handle_output',
        'classpath' => '',
        'description' => 'Handle external function response output',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_create' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_create',
        'classpath' => '',
        'description' => 'Webservice create',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_delete' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_delete',
        'classpath' => '',
        'description' => 'Webservice delete',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_state_switch' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_state_switch',
        'classpath' => '',
        'description' => 'Switch webservice setting state',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_token_create' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_token_create',
        'classpath' => '',
        'description' => 'Create webservice token',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_token_delete' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_token_delete',
        'classpath' => '',
        'description' => 'Delete webservice token',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_tokens_table_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_tokens_table_output',
        'classpath' => '',
        'description' => 'Tokens table output',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_user_delete' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_user_delete',
        'classpath' => '',
        'description' => 'Webservice user delete',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_users_table_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_users_table_output',
        'classpath' => '',
        'description' => 'Webservice users table output',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_function_add' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_function_add',
        'classpath' => '',
        'description' => 'Add webservice function',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_function_delete' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_function_delete',
        'classpath' => '',
        'description' => 'Delete webservice function',
        'type' => 'write',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_functions_table_output' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_functions_table_output',
        'classpath' => '',
        'description' => 'Webservice functions table output',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
    'local_wsmanager_webservice_rename' => [
        'classname' => 'local_wsmanager\external',
        'methodname' => 'webservice_rename',
        'classpath' => '',
        'description' => 'Webservice rename',
        'type' => 'read',
        'loginrequired' => true,
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
    ],
];
